import {
  Home,
  BrainCircuit,
  Calendar,
  Tractor,
  Settings,
  DollarSign,
  ShieldCheck,
  Database,
  Users,
  BookOpen,
  Github,
  LifeBuoy,
  Mail,
  TrendingUp,
  HelpCircle,
  BarChart2,
  CloudSun,
  Leaf,
  Beef,
  Layout,
  Coffee,
  LayoutGrid,
  Landmark,
  Bug,
  Layers,
  Milk,
  Fish,
  Droplet,
  Sprout,
  Map as MapIcon,
  Cpu,
  Award,
  Wheat,
  Warehouse,
  Truck,
  PawPrint,
  Hexagon
, Trees, Bird, Sun, Fence, ClipboardCheck, ScrollText, Key, Stethoscope, Briefcase, MessageCircle, Star, Pin } from 'lucide-react';

export const navigation = [
  { name: 'Dashboard', icon: Home, current: true },
  { name: 'Favorites', icon: Star, current: false },
  { name: 'My Pins', icon: Pin, current: false },
  { name: 'Intelligence', icon: BrainCircuit, current: false },
  { name: 'Planning', icon: Calendar, current: false },
  { name: 'Agriculture', icon: Tractor, current: false },
  { name: 'Operations', icon: Settings, current: false },
  { name: 'Economics', icon: DollarSign, current: false },
  { name: 'Compliance', icon: ShieldCheck, current: false, badge: 'Soon' },
  { name: 'Tools & Data', icon: Database, current: false },
  { name: 'Community', icon: Users, current: false },
  { name: 'Docs', icon: BookOpen, current: false },
];

export const summaryStats = [
  { name: 'Projects', value: '24', change: '+12%', changeType: 'positive', icon: Home, color: 'bg-green-100 text-green-700' },
  { name: 'Analyses', value: '156', change: '+18%', changeType: 'positive', icon: TrendingUp, color: 'bg-blue-100 text-blue-700' },
  { name: 'Datasets', value: '32', change: '+8%', changeType: 'positive', icon: Database, color: 'bg-purple-100 text-purple-700' },
  { name: 'Alerts', value: '7', change: '', changeType: 'neutral', icon: LifeBuoy, color: 'bg-orange-100 text-orange-700' }, // using LifeBuoy as placeholder for bell
];

export const tools = [

  { id: 'platform', name: 'Platform', description: 'The main home base. It’s the master dashboard where you can see all your apps, navigate between them, and customize your layout.', icon: Layout, color: 'text-gray-700', bg: 'bg-gray-100', url: 'https://ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Platform', longDescription: 'The main home base. It’s the master dashboard where you can see all your apps, navigate between them, and customize your layout.' },
  { id: 'forecast', name: 'Forecast', description: 'A market tracker. It looks at market trends to help you guess where crop and livestock prices are heading so you can sell at the right time.', icon: TrendingUp, color: 'text-green-600', bg: 'bg-green-50', url: 'https://forecast.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Forecast', longDescription: 'A market tracker. It looks at market trends to help you guess where crop and livestock prices are heading so you can sell at the right time.' },
  { id: 'whatif', name: 'WhatIf', description: 'The WhatIf engine is a rugged sensitivity analysis sandbox designed to stress-test your operation\'s financial assumptions before you commit real capital. By allowing users to scale critical dynamic parameters like unexpected diesel surges, sudden fertilizer spikes, or localized yield reductions, the tool visualizes risk boundaries and outcomes in real time. It serves as your operational safety valve, mapping out exact financial break-even points across worst-case and best-case variables.', icon: HelpCircle, color: 'text-blue-600', bg: 'bg-blue-50', url: 'https://whatif.RuralOpsTools.com', github: 'https://github.com/dsgiri/RuralOpsTools-WhatIf' },
  { id: 'plan', name: 'Plan', description: 'Your seasonal planner. Use it to sketch out budgets, assign chores to workers, and see where your cash is going before the season starts.', icon: Calendar, color: 'text-purple-600', bg: 'bg-purple-50', url: 'https://plan.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Plan', longDescription: 'Your seasonal planner. Use it to sketch out budgets, assign chores to workers, and see where your cash is going before the season starts.' },
  { id: 'predictor', name: 'Predictor', description: 'Your crystal ball. It uses your past farm data to predict harvest dates, yield amounts, and first-frost dates using standard math probabilities.', icon: BrainCircuit, color: 'text-teal-600', bg: 'bg-teal-50', url: 'https://predictor.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Predictor', longDescription: 'Your crystal ball. It uses your past farm data to predict harvest dates, yield amounts, and first-frost dates using standard math probabilities.' },
  { id: 'habitat', name: 'Habitat', description: 'The instruction manual. A public website that hosts guides and explains exactly how the math in each tool works.', icon: Sprout, color: 'text-green-700', bg: 'bg-green-50', url: 'https://habitat.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-habitat', longDescription: 'The instruction manual. A public website that hosts guides and explains exactly how the math in each tool works.' },
  { id: 'breaktime', name: 'BreakTime', description: 'A crew timer. A simple stopwatch to track worker breaks during hot days so everyone stays safe and you stay legal.', icon: Coffee, color: 'text-orange-700', bg: 'bg-orange-50', url: 'https://breaktime.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-BreakTime', longDescription: 'A crew timer. A simple stopwatch to track worker breaks during hot days so everyone stays safe and you stay legal.' },
  { id: 'grid', name: 'Grid', description: 'Emergency triage. A fast, simple checklist that helps you instantly rank your chores when everything breaks at once and you need to prioritize.', icon: LayoutGrid, color: 'text-gray-600', bg: 'bg-gray-50', url: 'https://grid.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Grid', longDescription: 'Emergency triage. A fast, simple checklist that helps you instantly rank your chores when everything breaks at once and you need to prioritize.' },
  { id: 'usda', name: 'USDA', description: 'Government paperwork helper. It helps you calculate your government program payments (like ARC/PLC) and keep track of strict federal deadlines.', icon: Landmark, color: 'text-blue-800', bg: 'bg-blue-50', url: 'https://usda.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-USDA', longDescription: 'Government paperwork helper. It helps you calculate your government program payments (like ARC/PLC) and keep track of strict federal deadlines.' },
  { id: 'carbon', name: 'Carbon', description: 'Emission tracker. It looks at your fuel usage and tractor work to give you a clean estimate of your farm\'s carbon footprint.', icon: Leaf, color: 'text-emerald-600', bg: 'bg-emerald-50', url: 'https://carbon.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Carbon', longDescription: 'Emission tracker. It looks at your fuel usage and tractor work to give you a clean estimate of your farm\'s carbon footprint.' },
  { id: 'weather', name: 'Weather', description: 'Field weather, stripped down. It loads instantly on weak cell signals to give you clean wind, rain, and temperature data so you know if you can spray or plant right now.', icon: CloudSun, color: 'text-orange-500', bg: 'bg-orange-50', url: 'https://weather.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Weather', longDescription: 'Field weather, stripped down. It loads instantly on weak cell signals to give you clean wind, rain, and temperature data so you know if you can spray or plant right now.' },
  { id: 'pest', name: 'Pest', description: 'Bug control. You track how many bugs you find in your traps, and it tells you the exact day it makes financial sense to spray before they ruin your crop.', icon: Bug, color: 'text-red-600', bg: 'bg-red-50', url: 'https://pest.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Pest', longDescription: 'Bug control. You track how many bugs you find in your traps, and it tells you the exact day it makes financial sense to spray before they ruin your crop.' },
  { id: 'soil', name: 'Soil', description: 'Dirt math. You plug in your lab soil test results, and it tells you exactly how much fertilizer you need to buy without overpaying for retail filler.', icon: Layers, color: 'text-amber-700', bg: 'bg-amber-50', url: 'https://soil.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Soil', longDescription: 'Dirt math. You plug in your lab soil test results, and it tells you exactly how much fertilizer you need to buy without overpaying for retail filler.' },
  { id: 'dairy', name: 'Dairy', description: 'Milk margins. Track daily milk volumes, fat levels, and feed costs to calculate your "Income Over Feed Cost" and protect your margins.', icon: Milk, color: 'text-blue-500', bg: 'bg-blue-50', url: 'https://dairy.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Dairy', longDescription: 'Milk margins. Track daily milk volumes, fat levels, and feed costs to calculate your "Income Over Feed Cost" and protect your margins.' },
  { id: 'aqua', name: 'Aqua', description: 'Fish and shrimp math. Tracks water oxygen levels, pump electricity costs, and fish weight to make water-farming predictable.', icon: Fish, color: 'text-cyan-600', bg: 'bg-cyan-50', url: 'https://aqua.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Aqua', longDescription: 'Fish and shrimp math. Tracks water oxygen levels, pump electricity costs, and fish weight to make water-farming predictable.' },
  { id: 'hydroponic', name: 'Hydroponic', description: 'Indoor water-growing. Tracks pH levels, nutrient balances, and indoor electricity costs for running vertical grow lights.', icon: Droplet, color: 'text-cyan-500', bg: 'bg-cyan-50', url: 'https://hydroponic.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Hydroponic', longDescription: 'Indoor water-growing. Tracks pH levels, nutrient balances, and indoor electricity costs for running vertical grow lights.' },
  { id: 'greenhouse', name: 'Greenhouse', description: 'Greenhouse costs. Calculates your startup building costs and your winter heating bill to make sure indoor growing makes financial sense.', icon: Sprout, color: 'text-green-500', bg: 'bg-green-50', url: 'https://greenhouse.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Greenhouse', longDescription: 'Greenhouse costs. Calculates your startup building costs and your winter heating bill to make sure indoor growing makes financial sense.' },
  { id: 'land', name: 'Land', description: 'Property evaluator. Helps you compare land prices, calculate fair cash rent, or decide if it\'s smarter to buy or lease a new parcel.', icon: MapIcon, color: 'text-emerald-700', bg: 'bg-emerald-50', url: 'https://land.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Land', longDescription: 'Property evaluator. Helps you compare land prices, calculate fair cash rent, or decide if it\'s smarter to buy or lease a new parcel.' },
  { id: 'price', name: 'Price', description: 'The quote builder. Use it to build customer quotes, check your profit margins, and find your absolute financial break-even line.', icon: DollarSign, color: 'text-green-600', bg: 'bg-green-50', url: 'https://price.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Price', longDescription: 'The quote builder. Use it to build customer quotes, check your profit margins, and find your absolute financial break-even line.' },
  { id: 'solve', name: 'Solve', description: 'Automation estimator. Figures out the total cost of installing remote field sensors, cellular gates, and automatic water valves before you buy them.', icon: Cpu, color: 'text-indigo-600', bg: 'bg-indigo-50', url: 'https://solve.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Solve', longDescription: 'Automation estimator. Figures out the total cost of installing remote field sensors, cellular gates, and automatic water valves before you buy them.' },
  { id: 'quality', name: 'Quality', description: 'Quality control log. A compliance notebook to log product batches, safety tests, and processing steps to protect you from legal liability.', icon: Award, color: 'text-amber-600', bg: 'bg-amber-50', url: 'https://quality.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Quality', longDescription: 'Quality control log. A compliance notebook to log product batches, safety tests, and processing steps to protect you from legal liability.' },
  { id: 'beef', name: 'Beef', description: 'Cattle economics. Track weight gains and current market prices so you know the exact week to send your calves to auction for peak profit.', icon: Beef, color: 'text-orange-800', bg: 'bg-orange-50', url: 'https://beef.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Beef', longDescription: 'Cattle economics. Track weight gains and current market prices so you know the exact week to send your calves to auction for peak profit.' },
  { id: 'feed', name: 'Feed', description: 'The Feed optimization tool utilizes a type-safe Pearson Square calculation engine to balance dry matter profiles, protein minimums, and cost-per-ton ration metrics. It allows managers to compare alternative raw commodity components to build the lowest-cost livestock diets while hitting absolute nutritional baselines. It targets feed waste, storage shrink, and delivery overhead to directly lower an operation\'s primary recurring cost variable.', icon: Wheat, color: 'text-yellow-600', bg: 'bg-yellow-50', url: 'https://feed.RuralOpsTools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Feed' },
  { id: 'storage', name: 'Storage', description: 'Bin capacity. Enter the dimensions of your grain bins, hay barns, or feed bunks, and it calculates exactly how many tons or bushels will fit inside.', icon: Warehouse, color: 'text-slate-600', bg: 'bg-slate-50', url: 'https://storage.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Storage', longDescription: 'Bin capacity. Enter the dimensions of your grain bins, hay barns, or feed bunks, and it calculates exactly how many tons or bushels will fit inside.' },
  { id: 'transport', name: 'Transport', description: 'Trucking costs. Calculates your fuel costs, driver hours, and empty mileage to tell you if it\'s cheaper to haul your own grain or hire a semi.', icon: Truck, color: 'text-slate-700', bg: 'bg-slate-50', url: 'https://transport.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Transport', longDescription: 'Trucking costs. Calculates your fuel costs, driver hours, and empty mileage to tell you if it\'s cheaper to haul your own grain or hire a semi.' },
  { id: 'livestock', name: 'Livestock', description: 'The master herd book. Track breeding calendars, pregnancy timelines, and growth charts for cattle, pigs, sheep, or goats in one place.', icon: PawPrint, color: 'text-orange-600', bg: 'bg-orange-50', url: 'https://livestock.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Livestock', longDescription: 'The master herd book. Track breeding calendars, pregnancy timelines, and growth charts for cattle, pigs, sheep, or goats in one place.' },
  { id: 'honeybee', name: 'Honeybee', description: 'Hive tracker. Log your honey yields, track queen health, and record mite treatments across all your bee yards.', icon: Hexagon, color: 'text-yellow-500', bg: 'bg-yellow-50', url: 'https://honeybee.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Honeybee', longDescription: 'Hive tracker. Log your honey yields, track queen health, and record mite treatments across all your bee yards.' },


  { id: 'wood', name: 'Wood', description: 'Timber calculator. Measure standing trees on your property, and it tells you how many usable boards you can get and what they are worth.', icon: Trees, color: 'text-amber-800', bg: 'bg-amber-100', url: 'https://wood.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-Wood', longDescription: 'Timber calculator. Measure standing trees on your property, and it tells you how many usable boards you can get and what they are worth.' },
  { id: 'poultry', name: 'Poultry', description: 'The coop logger. Count your daily eggs, track incubator hatch dates, and monitor bird losses to keep your flock profitable.', icon: Bird, color: 'text-orange-400', bg: 'bg-orange-100', url: 'https://poultry.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-pultry', longDescription: 'The coop logger. Count your daily eggs, track incubator hatch dates, and monitor bird losses to keep your flock profitable.' },
  { id: 'solar', name: 'Solar', description: 'Solar panel sizer. Figures out exactly how many solar panels and batteries you need to power remote well pumps, cameras, or electric gates.', icon: Sun, color: 'text-yellow-500', bg: 'bg-yellow-100', url: 'https://solar.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-comply', longDescription: 'Solar panel sizer. Figures out exactly how many solar panels and batteries you need to power remote well pumps, cameras, or electric gates.' },
  { id: 'fence', name: 'Fence', description: 'Fence line estimator. You measure your field, pick your wire type, and it tells you exactly how many posts, clips, and spools of wire to buy.', icon: Fence, color: 'text-stone-600', bg: 'bg-stone-100', url: 'https://fence.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-fense', longDescription: 'Fence line estimator. You measure your field, pick your wire type, and it tells you exactly how many posts, clips, and spools of wire to buy.' },
  { id: 'tractor', name: 'Tractor', description: 'Maintenance manual. A digital logbook to track oil changes, diesel consumption, and repairs across your trucks and tractors to prevent breakdowns.', icon: Tractor, color: 'text-red-500', bg: 'bg-red-100', url: 'https://tractor.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-tractor', longDescription: 'Maintenance manual. A digital logbook to track oil changes, diesel consumption, and repairs across your trucks and tractors to prevent breakdowns.' },
  { id: 'comply', name: 'Comply', description: 'Comply: Environmental runoff check-lists and local regulatory compliance logs.', icon: ClipboardCheck, color: 'text-blue-600', bg: 'bg-blue-100', url: 'https://comply.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-comply', longDescription: 'Comply: Environmental runoff check-lists and local regulatory compliance logs.' },
  { id: 'grant', name: 'Grant', description: 'Grant tracker. A compiled list of federal, state, and private conservation grants to help you apply for free farm improvement funding.', icon: ScrollText, color: 'text-emerald-700', bg: 'bg-emerald-100', url: 'https://grant.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-grant', longDescription: 'Grant tracker. A compiled list of federal, state, and private conservation grants to help you apply for free farm improvement funding.' },
  { id: 'stock', name: 'Stock', description: 'Tool & part inventory. A simple ledger to track spare parts, tools, and farm supplies so you don\'t run out of a belt or bolt during a busy harvest day.', icon: TrendingUp, color: 'text-indigo-500', bg: 'bg-indigo-100', url: 'https://stock.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-stock', longDescription: 'Tool & part inventory. A simple ledger to track spare parts, tools, and farm supplies so you don\'t run out of a belt or bolt during a busy harvest day.' },
  { id: 'rental', name: 'Rental', description: 'Renting vs. Loaning. Calculates if it makes financial sense to rent your equipment out to neighbors or rent land out to bring in extra cash.', icon: Key, color: 'text-teal-600', bg: 'bg-teal-100', url: 'https://rental.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-rental', longDescription: 'Renting vs. Loaning. Calculates if it makes financial sense to rent your equipment out to neighbors or rent land out to bring in extra cash.' },
  { id: 'vet', name: 'Vet', description: 'Medicine dosage checker. Enter an animal\'s weight, and it calculates the exact medical dose to give them, plus the date it\'s safe to sell the meat or milk.', icon: Stethoscope, color: 'text-rose-500', bg: 'bg-rose-100', url: 'https://vet.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-vet', longDescription: 'Medicine dosage checker. Enter an animal\'s weight, and it calculates the exact medical dose to give them, plus the date it\'s safe to sell the meat or milk.' },
  { id: 'jobs', name: 'Jobs', description: 'Local labor exchange. A simple job board built strictly to connect rural operations with seasonal harvest crews, tractor drivers, and farm hands.', icon: Briefcase, color: 'text-slate-600', bg: 'bg-slate-100', url: 'https://jobs.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-job', longDescription: 'Local labor exchange. A simple job board built strictly to connect rural operations with seasonal harvest crews, tractor drivers, and farm hands.' },
  { id: 'answer', name: 'Answer', description: 'The calculation solver. A search box where you can type any weird farming formula or structural math problem and get an immediate answer without ads.', icon: MessageCircle, color: 'text-cyan-500', bg: 'bg-cyan-100', url: 'https://answer.ruralopstools.com', github: 'https://github.com/dsgiri/RuralOpsTools-answer', longDescription: 'The calculation solver. A search box where you can type any weird farming formula or structural math problem and get an immediate answer without ads.' },
];

export const chartData = [
  { name: 'Apr 21', projects: 32, analyses: 15, alerts: 5 },
  { name: 'Apr 25', projects: 48, analyses: 25, alerts: 7 },
  { name: 'Apr 28', projects: 52, analyses: 28, alerts: 6 },
  { name: 'May 1', projects: 53, analyses: 30, alerts: 8 },
  { name: 'May 5', projects: 58, analyses: 33, alerts: 10 },
  { name: 'May 8', projects: 62, analyses: 38, alerts: 11 },
  { name: 'May 12', projects: 68, analyses: 42, alerts: 12 },
  { name: 'May 15', projects: 72, analyses: 44, alerts: 14 },
  { name: 'May 19', projects: 78, analyses: 48, alerts: 16 },
];

export const recentActivity = [
  { id: 1, title: 'Soil Analysis Completed', desc: 'Field 12A - Corn North', time: '2h ago', icon: Leaf, color: 'text-green-600', bg: 'bg-green-50' },
  { id: 2, title: 'Forecast Report Generated', desc: 'Corn Price Outlook - Q2 2025', time: '5h ago', icon: TrendingUp, color: 'text-blue-600', bg: 'bg-blue-50' },
  { id: 3, title: 'Weather Alert', desc: 'Freeze warning for Brazos County', time: '1d ago', icon: CloudSun, color: 'text-orange-500', bg: 'bg-orange-50' },
  { id: 4, title: 'Dataset Updated', desc: 'USDA NASS - QuickStats', time: '2d ago', icon: Database, color: 'text-purple-600', bg: 'bg-purple-50' },
  { id: 5, title: 'Project Shared', desc: 'Dairy Expansion Plan', time: '2d ago', icon: Users, color: 'text-green-600', bg: 'bg-green-50' },
];

export const announcements = [
  { id: 1, title: 'RuralOpsTools v1.0 Released 🎉', desc: 'The open source platform for rural intelligence is here.', date: 'May 20', icon: CloudSun },
  { id: 2, title: 'New: Carbon Benchmarking Tool', desc: 'Track and reduce emissions on your farm.', date: 'May 18', icon: TrendingUp },
  { id: 3, title: 'Community Update', desc: 'Thanks to 150+ contributors making this possible!', date: 'May 15', icon: Users },
  { id: 4, title: 'USDA Data Integration', desc: 'New datasets added for better decision making.', date: 'May 12', icon: Database },
];
