import {
  Home,
  BrainCircuit,
  Calendar,
  Tractor,
  Settings,
  DollarSign,
  ShieldCheck,
  Database,
  Users,
  BookOpen,
  Github,
  LifeBuoy,
  Mail,
  TrendingUp,
  HelpCircle,
  BarChart2,
  CloudSun,
  Leaf,
  Beef,
  Layout,
  Coffee,
  LayoutGrid,
  Landmark,
  Bug,
  Layers,
  Milk,
  Fish,
  Droplet,
  Sprout,
  Map as MapIcon,
  Cpu,
  Award,
  Wheat,
  Warehouse,
  Truck,
  PawPrint,
  Hexagon
, Trees, Bird, Sun, Fence, ClipboardCheck, ScrollText, Key, Stethoscope, Briefcase, MessageCircle,} from 'lucide-react';

export const navigation = [
  { name: 'Dashboard', icon: Home, current: true },
  { name: 'Intelligence', icon: BrainCircuit, current: false },
  { name: 'Planning', icon: Calendar, current: false },
  { name: 'Agriculture', icon: Tractor, current: false },
  { name: 'Operations', icon: Settings, current: false },
  { name: 'Economics', icon: DollarSign, current: false },
  { name: 'Compliance', icon: ShieldCheck, current: false, badge: 'Soon' },
  { name: 'Tools & Data', icon: Database, current: false },
  { name: 'Community', icon: Users, current: false },
  { name: 'Docs', icon: BookOpen, current: false },
  { name: 'GitHub', icon: Github, current: false },
  { name: 'Contact', icon: Mail, current: false },
  { name: 'Support', icon: LifeBuoy, current: false },
];

export const summaryStats = [
  { name: 'Projects', value: '24', change: '+12%', changeType: 'positive', icon: Home, color: 'bg-green-100 text-green-700' },
  { name: 'Analyses', value: '156', change: '+18%', changeType: 'positive', icon: TrendingUp, color: 'bg-blue-100 text-blue-700' },
  { name: 'Datasets', value: '32', change: '+8%', changeType: 'positive', icon: Database, color: 'bg-purple-100 text-purple-700' },
  { name: 'Alerts', value: '7', change: '', changeType: 'neutral', icon: LifeBuoy, color: 'bg-orange-100 text-orange-700' }, // using LifeBuoy as placeholder for bell
];

export const tools = [

  { id: 'platform', name: 'Platform', description: 'Main ecosystem hub', icon: Layout, color: 'text-gray-700', bg: 'bg-gray-100', url: 'https://ruralopstools.com' },
  { id: 'forecast', name: 'Forecast', description: 'Trends & outlooks', icon: TrendingUp, color: 'text-green-600', bg: 'bg-green-50', url: 'https://forecast.ruralopstools.com' },
  { id: 'whatif', name: 'WhatIf', description: 'Scenario analysis', icon: HelpCircle, color: 'text-blue-600', bg: 'bg-blue-50', url: 'https://whatif.ruralopstools.com' },
  { id: 'plan', name: 'Plan', description: 'Budgeting & workflows', icon: Calendar, color: 'text-purple-600', bg: 'bg-purple-50', url: 'https://plan.ruralopstools.com' },
  { id: 'predictor', name: 'Predictor', description: 'ML predictions', icon: BrainCircuit, color: 'text-teal-600', bg: 'bg-teal-50', url: 'https://predictor.ruralopstools.com' },
  { id: 'habitat', name: 'Habitat', description: 'Content & resources', icon: Sprout, color: 'text-green-700', bg: 'bg-green-50', url: 'https://habitat.ruralopstools.com' },
  { id: 'breaktime', name: 'BreakTime', description: 'Pause utility', icon: Coffee, color: 'text-orange-700', bg: 'bg-orange-50', url: 'https://breaktime.ruralopstools.com' },
  { id: 'grid', name: 'Grid', description: 'Quick decisions', icon: LayoutGrid, color: 'text-gray-600', bg: 'bg-gray-50', url: 'https://grid.ruralopstools.com' },
  { id: 'usda', name: 'USDA', description: 'Program hub', icon: Landmark, color: 'text-blue-800', bg: 'bg-blue-50', url: 'https://usda.ruralopstools.com' },
  { id: 'carbon', name: 'Carbon', description: 'Emissions tracking', icon: Leaf, color: 'text-emerald-600', bg: 'bg-emerald-50', url: 'https://carbon.ruralopstools.com' },
  { id: 'weather', name: 'Weather', description: 'Weather insights', icon: CloudSun, color: 'text-orange-500', bg: 'bg-orange-50', url: 'https://weather.ruralopstools.com' },
  { id: 'pest', name: 'Pest', description: 'IPM & scouting', icon: Bug, color: 'text-red-600', bg: 'bg-red-50', url: 'https://pest.ruralopstools.com' },
  { id: 'soil', name: 'Soil', description: 'Soil & nutrients', icon: Layers, color: 'text-amber-700', bg: 'bg-amber-50', url: 'https://soil.ruralopstools.com' },
  { id: 'dairy', name: 'Dairy', description: 'Dairy economics', icon: Milk, color: 'text-blue-500', bg: 'bg-blue-50', url: 'https://dairy.ruralopstools.com' },
  { id: 'aqua', name: 'Aqua', description: 'Aquaculture profit', icon: Fish, color: 'text-cyan-600', bg: 'bg-cyan-50', url: 'https://aqua.ruralopstools.com' },
  { id: 'hydroponic', name: 'Hydroponic', description: 'CEA planning', icon: Droplet, color: 'text-cyan-500', bg: 'bg-cyan-50', url: 'https://hydroponic.ruralopstools.com' },
  { id: 'greenhouse', name: 'Greenhouse', description: 'Protected ag', icon: Sprout, color: 'text-green-500', bg: 'bg-green-50', url: 'https://greenhouse.ruralopstools.com' },
  { id: 'land', name: 'Land', description: 'Valuation & parcel', icon: MapIcon, color: 'text-emerald-700', bg: 'bg-emerald-50', url: 'https://land.ruralopstools.com' },
  { id: 'price', name: 'Price', description: 'Prices & quotes', icon: DollarSign, color: 'text-green-600', bg: 'bg-green-50', url: 'https://price.ruralopstools.com' },
  { id: 'solve', name: 'Solve', description: 'IoT cost estimates', icon: Cpu, color: 'text-indigo-600', bg: 'bg-indigo-50', url: 'https://solve.ruralopstools.com' },
  { id: 'quality', name: 'Quality', description: 'QA/QC tracking', icon: Award, color: 'text-amber-600', bg: 'bg-amber-50', url: 'https://quality.ruralopstools.com' },
  { id: 'beef', name: 'Beef', description: 'Cattle economics', icon: Beef, color: 'text-orange-800', bg: 'bg-orange-50', url: 'https://beef.ruralopstools.com' },
  { id: 'feed', name: 'Feed', description: 'Ration planning', icon: Wheat, color: 'text-yellow-600', bg: 'bg-yellow-50', url: 'https://feed.ruralopstools.com' },
  { id: 'storage', name: 'Storage', description: 'Capacity planning', icon: Warehouse, color: 'text-slate-600', bg: 'bg-slate-50', url: 'https://storage.ruralopstools.com' },
  { id: 'transport', name: 'Transport', description: 'Freight & route', icon: Truck, color: 'text-slate-700', bg: 'bg-slate-50', url: 'https://transport.ruralopstools.com' },
  { id: 'livestock', name: 'Livestock', description: 'Multi-species herd', icon: PawPrint, color: 'text-orange-600', bg: 'bg-orange-50', url: 'https://livestock.ruralopstools.com' },
  { id: 'honeybee', name: 'Honeybee', description: 'Apiary & pollination', icon: Hexagon, color: 'text-yellow-500', bg: 'bg-yellow-50', url: 'https://honeybee.ruralopstools.com', github: 'https://github.com/dsgiri/ruralopstools-honeybee' },


  { id: 'wood', name: 'Wood', description: 'Timber and forestry logs', icon: Trees, color: 'text-amber-800', bg: 'bg-amber-100', url: 'https://wood.ruralopstools.com' },
  { id: 'poultry', name: 'Poultry', description: 'Egg production logs', icon: Bird, color: 'text-orange-400', bg: 'bg-orange-100', url: 'https://poultry.ruralopstools.com' },
  { id: 'solar', name: 'Solar', description: 'Off-grid solar array efficiency', icon: Sun, color: 'text-yellow-500', bg: 'bg-yellow-100', url: 'https://solar.ruralopstools.com' },
  { id: 'fence', name: 'Fence', description: 'Linear acreage calculator', icon: Fence, color: 'text-stone-600', bg: 'bg-stone-100', url: 'https://fence.ruralopstools.com' },
  { id: 'tractor', name: 'Tractor', description: 'Fleet maintenance logger', icon: Tractor, color: 'text-red-500', bg: 'bg-red-100', url: 'https://tractor.ruralopstools.com' },
  { id: 'comply', name: 'Comply', description: 'Regulatory compliance logs', icon: ClipboardCheck, color: 'text-blue-600', bg: 'bg-blue-100', url: 'https://comply.ruralopstools.com' },
  { id: 'grant', name: 'Grant', description: 'Agricultural funding options', icon: ScrollText, color: 'text-emerald-700', bg: 'bg-emerald-100', url: 'https://grant.ruralopstools.com' },
  { id: 'stock', name: 'Stock', description: 'Livestock and market stock', icon: TrendingUp, color: 'text-indigo-500', bg: 'bg-indigo-100', url: 'https://stock.ruralopstools.com' },
  { id: 'rental', name: 'Rental', description: 'Equipment rental tracking', icon: Key, color: 'text-teal-600', bg: 'bg-teal-100', url: 'https://rental.ruralopstools.com' },
  { id: 'vet', name: 'Vet', description: 'Veterinary health records', icon: Stethoscope, color: 'text-rose-500', bg: 'bg-rose-100', url: 'https://vet.ruralopstools.com' },
  { id: 'jobs', name: 'Jobs', description: 'Rural labor and job tracking', icon: Briefcase, color: 'text-slate-600', bg: 'bg-slate-100', url: 'https://jobs.ruralopstools.com' },
  { id: 'answer', name: 'Answer', description: 'Q&A and knowledge base', icon: MessageCircle, color: 'text-cyan-500', bg: 'bg-cyan-100', url: 'https://answer.ruralopstools.com' },
];

export const chartData = [
  { name: 'Apr 21', projects: 32, analyses: 15, alerts: 5 },
  { name: 'Apr 25', projects: 48, analyses: 25, alerts: 7 },
  { name: 'Apr 28', projects: 52, analyses: 28, alerts: 6 },
  { name: 'May 1', projects: 53, analyses: 30, alerts: 8 },
  { name: 'May 5', projects: 58, analyses: 33, alerts: 10 },
  { name: 'May 8', projects: 62, analyses: 38, alerts: 11 },
  { name: 'May 12', projects: 68, analyses: 42, alerts: 12 },
  { name: 'May 15', projects: 72, analyses: 44, alerts: 14 },
  { name: 'May 19', projects: 78, analyses: 48, alerts: 16 },
];

export const recentActivity = [
  { id: 1, title: 'Soil Analysis Completed', desc: 'Field 12A - Corn North', time: '2h ago', icon: Leaf, color: 'text-green-600', bg: 'bg-green-50' },
  { id: 2, title: 'Forecast Report Generated', desc: 'Corn Price Outlook - Q2 2025', time: '5h ago', icon: TrendingUp, color: 'text-blue-600', bg: 'bg-blue-50' },
  { id: 3, title: 'Weather Alert', desc: 'Freeze warning for Brazos County', time: '1d ago', icon: CloudSun, color: 'text-orange-500', bg: 'bg-orange-50' },
  { id: 4, title: 'Dataset Updated', desc: 'USDA NASS - QuickStats', time: '2d ago', icon: Database, color: 'text-purple-600', bg: 'bg-purple-50' },
  { id: 5, title: 'Project Shared', desc: 'Dairy Expansion Plan', time: '2d ago', icon: Users, color: 'text-green-600', bg: 'bg-green-50' },
];

export const announcements = [
  { id: 1, title: 'RuralOpsTools v1.0 Released 🎉', desc: 'The open source platform for rural intelligence is here.', date: 'May 20', icon: CloudSun },
  { id: 2, title: 'New: Carbon Benchmarking Tool', desc: 'Track and reduce emissions on your farm.', date: 'May 18', icon: TrendingUp },
  { id: 3, title: 'Community Update', desc: 'Thanks to 150+ contributors making this possible!', date: 'May 15', icon: Users },
  { id: 4, title: 'USDA Data Integration', desc: 'New datasets added for better decision making.', date: 'May 12', icon: Database },
];
